import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@components/ui/theme-provider";
import { Provider } from "@src/context";
import dynamic from "next/dynamic";
import Layout from "@src/components/layout";
import localFont from "next/font/local";
export const metadata: Metadata = {
  title: "TODO",
  description: "Generated by create next app",
};

const LoginModal = dynamic(() => import("@src/components/modals/login-modal"), {
  ssr: false,
});
const acuminProBookFont = localFont({
  src: "../libs/fonts/Acumin-Pro-Book.otf",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className='bg-background text-foreground'>
        <div className={acuminProBookFont.className}>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <Provider>
              <Layout>{children}</Layout>
              <LoginModal />
            </Provider>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
