import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@components/ui/theme-provider";
import { Provider } from "@src/context";
import dynamic from "next/dynamic";
import Nav from "@src/components/nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NoSSR = dynamic(() => import("@src/components/modals/login-modal"), {
  ssr: false,
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className='bg-background text-foreground'>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Provider>
            <Nav isMounted={true} />
            <div className='grid w-screen h-screen grid-cols-12'>
              <div className='h-full col-span-2'></div>
              <div className='h-full col-span-8'>{children}</div>
              <div className='h-full col-span-2'></div>
            </div>
            <NoSSR />
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
